---
title: Sound machine
hero_image: images/banner.png
description: Create a sound machine that will play sound effects or music using buttons,
  switches, or a potentiometer
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Design your sound machine
- title: Compose your sounds
  completion:
  - engaged
- title: Control your sounds
- title: Craft your device
  completion:
  - internal
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
  - external
- title: Upgrade your project
- title: Share
- title: What next?
